# sends test-coverage data to codecov.io
# https://codecov.io/gh/spencermountain/compromise
name: Coverage

on:
  release:
    types: [created]

jobs:
  getCoverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
  
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: '20'
          cache: npm
          check-latest: true

      - run: npm ci
      - run: npm i -g c8 codecov
      - run: c8 -r lcov -n 'src/**/*' -n 'plugins/**/*' npm run test && codecov -t 15039ad1-b495-48cd-b4a0-bcf124c9b318
      # - run: npm run codecov
